import pandas as pd
from flask import Flask, render_template, request, jsonify
import pickle
import warnings
warnings.filterwarnings('ignore')

# Initialize the Flask application
app = Flask(__name__)

# Load the pre-processed data and trained model generated by your Notebook
try:
    zomato_df = pd.read_csv("restaurant1.csv")
    df_percent = zomato_df.copy()
    df_percent.set_index('name', inplace=True)
    indices = pd.Series(df_percent.index)

    with open("restaurant.pkl", "rb") as f:
        cosine_similarities = pickle.load(f)
except FileNotFoundError:
    print("Error: Please run the Jupyter Notebook first to generate the model and CSV.")

# Recommendation Logic
def recommend(name, cosine_similarities=cosine_similarities):
    recommend_restaurant = []
    
    # Check if the exact name exists in our database
    if name not in indices.values:
        return pd.DataFrame(columns=['Error: Restaurant not found in database. Please use the autocomplete suggestions.'])

    # Find the index of the target restaurant
    idx = indices[indices == name].index[0]
    
    # Get similarity scores and sort them
    score_series = pd.Series(cosine_similarities[idx]).sort_values(ascending=False)
    
    # Get the top 30 similar restaurants (we grab extra to account for duplicates we might drop)
    top_indexes = list(score_series.iloc[1:min(31, len(score_series))].index)
    
    for each in top_indexes:
        recommend_restaurant.append(list(df_percent.index)[each])
    
    df_new = pd.DataFrame(columns=['cuisines', 'Mean Rating', 'cost'])
    
    # Rebuild a dataframe with the recommended restaurants
    for each in recommend_restaurant:
        selected_data = df_percent[['cuisines', 'Mean Rating', 'cost']][df_percent.index == each]
        if not selected_data.empty:
            df_new = pd.concat([df_new, selected_data.sample(n=1)])
    
    # Clean up, remove duplicates, and sort by highest rating
    df_new = df_new.drop_duplicates(subset=['cuisines', 'Mean Rating', 'cost'], keep=False)
    df_new = df_new.sort_values(by='Mean Rating', ascending=False).head(10)
    
    # Format the column names to look clean on the frontend HTML table
    df_new.rename(columns={'cuisines': 'Cuisines', 'Mean Rating': 'Rating (out of 5)', 'cost': 'Cost for Two (₹)'}, inplace=True)
    return df_new

# --- Web Routes ---

@app.route('/')
def home():
    # Renders the Light Mode landing page
    return render_template('index.html')

@app.route('/web')
def web():
    # Renders the Search Input page
    return render_template('web.html')

@app.route('/result', methods=['POST'])
def result():
    # Handles the form submission and renders the results dashboard
    output = request.form['output']
    res = recommend(output)
    
    # Convert the resulting Pandas DataFrame directly to HTML
    html_table = res.to_html(classes='custom-table', justify='left', border=0, index=True, index_names=False)
    
    return render_template('result.html', keyword=html_table, search_term=output)

@app.route('/autocomplete', methods=['GET'])
def autocomplete():
    # Handles the dynamic search suggestions as the user types
    search_term = request.args.get('term', '').lower()
    
    if not search_term:
        return jsonify([])
        
    # Find names that contain the search term (case-insensitive)
    matches = df_percent[df_percent.index.str.lower().str.contains(search_term, na=False)].index.tolist()
    
    # Remove duplicates, sort alphabetically, and return top 10
    matches = sorted(list(set(matches)))
    return jsonify(matches[:10])

# Run the application
if __name__ == '__main__':
    app.run(debug=True)